version: '3.8'

services:
  redis-main:
    image: redis:7-alpine
    container_name: mesh-redis-main
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes --port 6379
    volumes:
      - redis-main-data:/data

  redis-agent:
    image: redis:7-alpine
    container_name: mesh-redis-agent
    ports:
      - "6380:6380"
    restart: unless-stopped
    command: redis-server --appendonly yes --port 6380
    volumes:
      - redis-agent-data:/data

  agent-service:
    build:
      context: ./agent-service
      dockerfile: Dockerfile
    container_name: mesh-agent-service
    ports:
      - "8081:8081"
    depends_on:
      - redis-agent
    environment:
      - SPRING_REDIS_HOST=redis-agent
      - SPRING_REDIS_PORT=6380
    restart: unless-stopped

  cluster-service:
    build:
      context: ./cluster-service
      dockerfile: Dockerfile
    container_name: mesh-cluster-service
    ports:
      - "8082:8082"
    restart: unless-stopped

  cluster-management-service:
    build:
      context: ./cluster-management-service
      dockerfile: Dockerfile
    container_name: mesh-cluster-management-service
    ports:
      - "8083:8083"
    depends_on:
      - redis-main
    environment:
      - SPRING_REDIS_HOST=redis-main
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis-main-data:
  redis-agent-data: 