# Agent Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: mesh-manager
  labels:
    app: agent-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: your-registry/mesh-agent-service:latest  # 실제 이미지 경로로 변경
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: mesh-manager
  labels:
    app: agent-service
spec:
  type: LoadBalancer
  selector:
    app: agent-service
  ports:
  - port: 8081
    targetPort: 8081

---
# Cluster Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-service
  namespace: mesh-manager
  labels:
    app: cluster-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-service
  template:
    metadata:
      labels:
        app: cluster-service
    spec:
      containers:
      - name: cluster-service
        image: your-registry/mesh-cluster-service:latest  # 실제 이미지 경로로 변경
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  namespace: mesh-manager
  labels:
    app: cluster-service
spec:
  type: LoadBalancer
  selector:
    app: cluster-service
  ports:
  - port: 8082
    targetPort: 8082

---
# Cluster Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-management-service
  namespace: mesh-manager
  labels:
    app: cluster-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-management-service
  template:
    metadata:
      labels:
        app: cluster-management-service
    spec:
      containers:
      - name: cluster-management-service
        image: your-registry/mesh-cluster-management-service:latest  # 실제 이미지 경로로 변경
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-management-service
  namespace: mesh-manager
  labels:
    app: cluster-management-service
spec:
  type: LoadBalancer
  selector:
    app: cluster-management-service
  ports:
  - port: 8083
    targetPort: 8083 