spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clusterResourceDB
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083

  data:
    redis:
      host: localhost
      port: 6379