spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mesh_manager_db?useSSL=false&serverTimezone=UTC
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379